export const countrySlugs = [
  "pakistan", "saudi-arabia", "united-arab-emirates",
  "united-kingdom", "united-states", "canada", "australia",
  "turkey", "malaysia", "indonesia", "bangladesh", "egypt",
  "india", "qatar", "kuwait", "oman", "bahrain", "iraq",
  "jordan", "lebanon", "syria", "yemen", "libya", "tunisia",
  "morocco", "algeria", "afghanistan", "palestine", "iran",
  "south-africa", "namibia", "botswana", "lesotho", "swaziland",
  "kenya", "tanzania", "uganda", "rwanda", "burundi", "mozambique",
  "zambia", "zimbabwe", "angola", "cameroon", "congo", "gabon",
  "ghana", "guinea", "guinea-bissau", "ivory-coast", "liberia",
  "mali", "mauritania", "mauritius", "niger", "nigeria", "senegal",
  "sierra-leone", "somalia", "south-sudan", "sudan", "benin",
  "burkina-faso", "cape-verde", "central-african-republic", "chad",
  "comoros", "democratic-republic-of-congo", "djibouti",
  "equatorial-guinea", "eritrea", "ethiopia", "gambia", "madagascar",
  "malawi", "sao-tome-and-principe", "seychelles", "togo",
  "armenia", "azerbaijan", "brunei", "cambodia", "china", "georgia",
  "hong-kong", "japan", "kazakhstan", "kyrgyzstan", "laos",
  "maldives", "mongolia", "myanmar", "nepal", "north-korea",
  "philippines", "singapore", "south-korea", "sri-lanka", "taiwan",
  "tajikistan", "thailand", "timor-leste", "turkmenistan", "uzbekistan",
  "vietnam", "albania", "austria", "belgium", "bosnia-and-herzegovina",
  "bulgaria", "croatia", "cyprus", "czech-republic", "denmark",
  "finland", "france", "germany", "greece", "hungary", "ireland",
  "italy", "kosovo", "latvia", "lithuania", "luxembourg", "malta",
  "moldova", "montenegro", "netherlands", "north-macedonia", "norway",
  "poland", "portugal", "romania", "russia", "serbia", "slovakia",
  "slovenia", "spain", "sweden", "switzerland", "ukraine",
  "argentina", "bolivia", "brazil", "chile", "colombia", "costa-rica",
  "cuba", "dominican-republic", "ecuador", "el-salvador", "guatemala",
  "guyana", "haiti", "honduras", "jamaica", "mexico", "nicaragua",
  "panama", "paraguay", "peru", "suriname", "trinidad-and-tobago",
  "uruguay", "venezuela", "fiji", "new-zealand", "papua-new-guinea",
  "solomon-islands", "vanuatu",
];