import { MetadataRoute } from "next";

const countries: Record<string, string[]> = {
  pakistan: ["Karachi","Lahore","Islamabad","Faisalabad","Multan","Peshawar","Quetta","Rawalpindi","Sialkot","Gujranwala","Hyderabad","Sukkur","Bahawalpur","Sargodha","Dera Ghazi Khan","Sheikhupura","Jhang","Gujrat","Sahiwal","Larkana","Mardan","Abbottabad","Mirpur","Nawabshah","Mingora","Rahim Yar Khan","Okara","Kasur","Dera Ismail Khan","Muzaffarabad","Gilgit","Jhelum","Wah Cantonment","Kamoke","Hafizabad","Chiniot","Khanewal","Pakpattan","Mandi Bahauddin","Toba Tek Singh","Kohat","Bannu","Mansehra","Nowshera","Charsadda","Turbat","Gwadar","Khuzdar","Jacobabad","Layyah"],
  "saudi-arabia": ["Mecca","Medina","Riyadh","Jeddah","Dammam","Taif","Tabuk","Abha","Khobar","Jubail","Yanbu","Najran","Hail","Buraidah","Khamis Mushait","Al Qatif","Al Hufuf","Arar","Sakaka","Jizan","Al Bahah","Dawadmi","Zulfi","Wajh","Qurayyat"],
  "united-arab-emirates": ["Dubai","Abu Dhabi","Sharjah","Ajman","Al Ain","Ras Al Khaimah","Fujairah","Umm Al Quwain","Khor Fakkan","Kalba","Dhaid","Madinat Zayed","Ruwais","Liwa Oasis"],
  "united-kingdom": ["London","Manchester","Birmingham","Leeds","Bradford","Glasgow","Sheffield","Liverpool","Edinburgh","Coventry","Leicester","Nottingham","Bristol","Cardiff","Belfast","Derby","Luton","Wolverhampton","Southampton","Portsmouth","Stoke-on-Trent","Bolton","Blackburn","Oldham","Rochdale","Huddersfield","Halifax","Dewsbury","Slough","Walsall"],
  "united-states": ["New York","Chicago","Houston","Los Angeles","Dallas","Detroit","Philadelphia","Phoenix","San Antonio","San Diego","Jacksonville","Columbus","San Jose","Austin","Fort Worth","Charlotte","Indianapolis","Seattle","Denver","Washington","Nashville","Oklahoma City","El Paso","Boston","Memphis","Atlanta","Minneapolis","Tampa","New Orleans","Baltimore"],
  canada: ["Toronto","Vancouver","Montreal","Calgary","Ottawa","Edmonton","Winnipeg","Hamilton","Quebec City","Brampton","Mississauga","Surrey","Laval","Halifax","London","Markham","Vaughan","Gatineau","Saskatoon","Longueuil","Burnaby","Regina","Richmond","Richmond Hill","Oakville"],
  australia: ["Sydney","Melbourne","Brisbane","Perth","Adelaide","Gold Coast","Canberra","Newcastle","Wollongong","Hobart","Geelong","Townsville","Cairns","Darwin","Toowoomba","Ballarat","Bendigo","Albury","Launceston","Mackay"],
  turkey: ["Istanbul","Ankara","Izmir","Bursa","Antalya","Adana","Konya","Gaziantep","Kayseri","Mersin","Eskisehir","Diyarbakir","Samsun","Denizli","Sakarya","Malatya","Trabzon","Erzurum","Van","Kahramanmaras"],
  malaysia: ["Kuala Lumpur","Penang","Johor Bahru","Kota Kinabalu","Kuching","Ipoh","Shah Alam","Petaling Jaya","Subang Jaya","Klang","Ampang","Kajang","Seremban","Kota Bharu","Kuala Terengganu","Alor Setar","Miri","Sandakan","Tawau","Sibu"],
  indonesia: ["Jakarta","Surabaya","Bandung","Medan","Makassar","Semarang","Palembang","Tangerang","Bekasi","Depok","Batam","Pekanbaru","Bandar Lampung","Padang","Malang","Bogor","Denpasar","Samarinda","Tasikmalaya","Balikpapan"],
  bangladesh: ["Dhaka","Chittagong","Sylhet","Rajshahi","Khulna","Comilla","Narayanganj","Gazipur","Mymensingh","Rangpur","Barishal","Jessore","Bogra","Tongi","Brahmanbaria","Saidpur","Tangail","Jamalpur","Pabna","Narsingdi"],
  egypt: ["Cairo","Alexandria","Giza","Shubra El Kheima","Port Said","Suez","Luxor","Asyut","Sharm el-Sheikh","Hurghada","Mansoura","Tanta","Zagazig","Ismailia","Faiyum","Damietta","Aswan","Minya","Beni Suef","Sohag"],
  india: ["Delhi","Mumbai","Hyderabad","Chennai","Kolkata","Bangalore","Lucknow","Patna","Jaipur","Ahmedabad","Surat","Pune","Bhopal","Kanpur","Nagpur","Indore","Agra","Varanasi","Meerut","Aligarh"],
  qatar: ["Doha","Al Rayyan","Al Wakrah","Al Khor","Mesaieed","Dukhan","Al Shamal","Umm Salal"],
  kuwait: ["Kuwait City","Salmiya","Hawalli","Farwaniya","Ahmadi","Jahra","Mubarak Al Kabeer"],
  oman: ["Muscat","Sohar","Salalah","Nizwa","Sur","Ibra","Buraimi","Rustaq","Khasab"],
  bahrain: ["Manama","Riffa","Muharraq","Hamad Town","Isa Town"],
  iraq: ["Baghdad","Basra","Mosul","Erbil","Kirkuk","Najaf","Karbala","Sulaymaniyah","Fallujah","Ramadi","Tikrit","Baqubah","Amarah","Nasiriyah","Samawa"],
  jordan: ["Amman","Zarqa","Irbid","Russeifa","Aqaba","Madaba","Salt","Mafraq","Jerash","Karak","Ajloun","Tafilah"],
  lebanon: ["Beirut","Tripoli","Sidon","Tyre","Zahle","Jounieh","Nabatieh","Baalbek","Byblos","Aley"],
  syria: ["Damascus","Aleppo","Homs","Latakia","Hama","Deir ez-Zor","Raqqa","Tartus","Idlib","Qamishli","Daraa","Sweida"],
  yemen: ["Sanaa","Aden","Taiz","Hodeidah","Ibb","Dhamar","Mukalla","Hajjah","Amran","Saada","Marib","Zinjibar"],
  libya: ["Tripoli","Benghazi","Misrata","Tarhuna","Zawiya","Ajdabiya","Derna","Bayda","Sirte","Tobruk","Sabha","Zliten"],
  tunisia: ["Tunis","Sfax","Sousse","Ettadhamen","Kairouan","Bizerte","Gabes","Ariana","Gafsa","Monastir","Tataouine","Nabeul"],
  morocco: ["Casablanca","Rabat","Fes","Marrakech","Agadir","Tangier","Meknes","Oujda","Kenitra","Tetouan","Safi","El Jadida","Beni Mellal","Nador","Khouribga"],
  algeria: ["Algiers","Oran","Constantine","Annaba","Blida","Batna","Djelfa","Setif","Sidi Bel Abbes","Biskra","Tebessa","El Oued","Skikda","Tiaret","Bejaia"],
  afghanistan: ["Kabul","Kandahar","Herat","Mazar-i-Sharif","Kunduz","Jalalabad","Ghazni","Balkh","Baghlan","Lashkar Gah","Taloqan","Pul-e-Khumri"],
  palestine: ["Gaza","Ramallah","Nablus","Hebron","Jenin","Tulkarm","Jericho","Bethlehem","Qalqilya","Khan Yunis"],
  iran: ["Tehran","Mashhad","Isfahan","Karaj","Tabriz","Shiraz","Qom","Ahvaz","Kermanshah","Rasht","Zahedan","Hamadan","Arak","Yazd","Ardabil"],
  israel: ["Jerusalem","Tel Aviv","Haifa","Rishon LeZion","Petah Tikva","Ashdod","Netanya","Beer Sheva","Holon","Bnei Brak","Nazareth","Jaffa"],
  "south-africa": ["Johannesburg","Cape Town","Durban","Pretoria","Port Elizabeth","Bloemfontein","East London","Nelspruit","Polokwane","Kimberley","Rustenburg","Pietermaritzburg"],
  namibia: ["Windhoek","Walvis Bay","Swakopmund","Rundu","Oshakati","Katima Mulilo","Grootfontein","Rehoboth"],
  botswana: ["Gaborone","Francistown","Molepolole","Selebi-Phikwe","Maun","Serowe","Kanye","Mahalapye"],
  lesotho: ["Maseru","Teyateyaneng","Mafeteng","Hlotse","Mohale's Hoek","Quthing","Qacha's Nek"],
  swaziland: ["Mbabane","Manzini","Lobamba","Nhlangano","Siteki","Big Bend","Pigg's Peak"],
  kenya: ["Nairobi","Mombasa","Kisumu","Nakuru","Eldoret","Thika","Malindi","Kitale","Garissa","Kakamega","Nyeri","Machakos"],
  tanzania: ["Dar es Salaam","Mwanza","Arusha","Dodoma","Mbeya","Morogoro","Tanga","Zanzibar","Kigoma","Tabora","Iringa","Songea"],
  uganda: ["Kampala","Gulu","Lira","Mbarara","Jinja","Bwizibwera","Mbale","Mukono","Kasese","Masaka","Hoima","Fort Portal"],
  rwanda: ["Kigali","Butare","Gitarama","Ruhengeri","Gisenyi","Byumba","Cyangugu","Kibungo","Rwamagana"],
  burundi: ["Bujumbura","Gitega","Ngozi","Rumonge","Bururi","Rutana","Muramvya","Kayanza"],
  mozambique: ["Maputo","Matola","Beira","Nampula","Chimoio","Quelimane","Tete","Nacala","Lichinga","Pemba"],
  zambia: ["Lusaka","Kitwe","Ndola","Kabwe","Chingola","Mufulira","Livingstone","Luanshya","Kasama","Chipata"],
  zimbabwe: ["Harare","Bulawayo","Chitungwiza","Mutare","Gweru","Kwekwe","Kadoma","Masvingo","Chinhoyi","Norton"],
  angola: ["Luanda","Huambo","Lobito","Benguela","Kuito","Lubango","Malanje","Namibe","Soyo","Cabinda"],
  cameroon: ["Yaounde","Douala","Garoua","Bamenda","Maroua","Bafoussam","Ngaoundere","Bertoua","Loum","Kumba"],
  congo: ["Brazzaville","Pointe-Noire","Dolisie","Nkayi","Impfondo","Ouesso","Owando","Madingou"],
  gabon: ["Libreville","Port-Gentil","Franceville","Oyem","Moanda","Mouila","Lambarene","Tchibanga"],
  ghana: ["Accra","Kumasi","Tamale","Sekondi-Takoradi","Cape Coast","Obuasi","Tema","Koforidua","Sunyani","Ho"],
  guinea: ["Conakry","Nzerekore","Kindia","Kankan","Labe","Kissidougou","Gueckedou","Boke"],
  "guinea-bissau": ["Bissau","Bafata","Gabu","Bissorã","Bolama","Cacheu","Bubaque","Mansoa"],
  "ivory-coast": ["Abidjan","Bouake","Daloa","Yamoussoukro","Korhogo","San-Pedro","Man","Divo","Gagnoa","Abengourou"],
  liberia: ["Monrovia","Gbarnga","Kakata","Bensonville","Harper","Voinjama","Buchanan","Zwedru"],
  mali: ["Bamako","Sikasso","Mopti","Koutiala","Kayes","Segou","Gao","Timbuktu","Kidal","San"],
  mauritania: ["Nouakchott","Nouadhibou","Nema","Kaedi","Rosso","Atar","Zouerate","Kiffa"],
  mauritius: ["Port Louis","Beau Bassin","Vacoas","Curepipe","Quatre Bornes","Triolet","Rose Hill","Mahebourg"],
  niger: ["Niamey","Zinder","Maradi","Agadez","Tahoua","Dosso","Arlit","Diffa"],
  nigeria: ["Lagos","Kano","Ibadan","Abuja","Port Harcourt","Benin City","Maiduguri","Zaria","Aba","Jos","Ilorin","Oyo","Enugu","Abeokuta","Kaduna","Sokoto","Katsina"],
  senegal: ["Dakar","Touba","Thies","Rufisque","Kaolack","Ziguinchor","Saint-Louis","Mbour","Diourbel","Louga"],
  "sierra-leone": ["Freetown","Bo","Kenema","Makeni","Koidu","Lunsar","Port Loko","Bonthe"],
  somalia: ["Mogadishu","Hargeisa","Bosasso","Kismayo","Berbera","Merca","Baidoa","Garowe","Beledweyne","Jilib"],
  "south-sudan": ["Juba","Wau","Malakal","Yei","Aweil","Torit","Rumbek","Bentiu","Bor","Kuajok"],
  sudan: ["Khartoum","Omdurman","Kassala","Port Sudan","Obeid","Wad Madani","Atbara","El Fasher","Nyala","Gedaref","Kosti","Rabak"],
  benin: ["Cotonou","Porto-Novo","Parakou","Abomey","Kandi","Ouidah","Lokossa","Natitingou"],
  "burkina-faso": ["Ouagadougou","Bobo-Dioulasso","Koudougou","Ouahigouya","Banfora","Dedougou","Kaya","Tenkodogo"],
  "cape-verde": ["Praia","Mindelo","Santa Maria","Assomada","Pedra Badejo"],
  "central-african-republic": ["Bangui","Bimbo","Berbérati","Carnot","Bambari","Bouar","Bossangoa","Bangassou"],
  chad: ["N'Djamena","Moundou","Sarh","Abeche","Kelo","Koumra","Pala","Am Timan"],
  comoros: ["Moroni","Mutsamudu","Fomboni","Domoni","Tsangadjou"],
  "democratic-republic-of-congo": ["Kinshasa","Lubumbashi","Mbuji-Mayi","Kananga","Kisangani","Bukavu","Tshikapa","Kolwezi","Likasi","Goma","Matadi","Uvira"],
  djibouti: ["Djibouti City","Ali Sabieh","Tadjoura","Obock","Dikhil","Arta"],
  "equatorial-guinea": ["Malabo","Bata","Ebebiyin","Aconibe","Annobon","Luba"],
  eritrea: ["Asmara","Keren","Massawa","Assab","Mendefera","Dekemhare","Adi Keyh"],
  ethiopia: ["Addis Ababa","Dire Dawa","Mekelle","Gondar","Hawassa","Bahir Dar","Dessie","Jimma","Jijiga","Shashamane"],
  gambia: ["Banjul","Serekunda","Brikama","Bakau","Farafenni","Lamin","Sukuta"],
  madagascar: ["Antananarivo","Toamasina","Antsirabe","Fianarantsoa","Mahajanga","Toliara","Antsiranana"],
  malawi: ["Lilongwe","Blantyre","Mzuzu","Zomba","Kasungu","Mangochi","Karonga","Salima"],
  "sao-tome-and-principe": ["Sao Tome","Santo Antonio","Neves"],
  seychelles: ["Victoria","Anse Boileau","Beau Vallon"],
  togo: ["Lome","Sokode","Kara","Atakpame","Dapaong","Tsevie","Aného","Bassar"],
  armenia: ["Yerevan","Gyumri","Vanadzor","Vagharshapat","Hrazdan","Abovyan","Kapan"],
  azerbaijan: ["Baku","Ganja","Sumgait","Mingachevir","Nakhchivan","Shirvan","Lankaran"],
  brunei: ["Bandar Seri Begawan","Kuala Belait","Seria","Tutong","Bangar"],
  cambodia: ["Phnom Penh","Siem Reap","Battambang","Sihanoukville","Kampong Cham","Pursat","Kampot","Takeo"],
  china: ["Beijing","Shanghai","Guangzhou","Shenzhen","Chengdu","Tianjin","Wuhan","Chongqing","Nanjing","Xi'an","Hangzhou","Urumqi","Kunming","Harbin","Qingdao"],
  georgia: ["Tbilisi","Kutaisi","Batumi","Rustavi","Gori","Zugdidi","Poti","Samtredia"],
  "hong-kong": ["Hong Kong Island","Kowloon","Mong Kok","Tsim Sha Tsui","Sha Tin","Tuen Mun","Yuen Long"],
  japan: ["Tokyo","Osaka","Yokohama","Nagoya","Sapporo","Kobe","Kyoto","Fukuoka","Kawasaki","Hiroshima","Sendai","Chiba"],
  kazakhstan: ["Almaty","Nur-Sultan","Shymkent","Karaganda","Aktobe","Taraz","Pavlodar","Ust-Kamenogorsk","Semey"],
  kyrgyzstan: ["Bishkek","Osh","Jalal-Abad","Karakol","Tokmok","Uzgen","Naryn"],
  laos: ["Vientiane","Luang Prabang","Savannakhet","Pakse","Thakhek","Xam Neua","Phonsavan"],
  maldives: ["Male","Addu City","Fuvahmulah","Kulhudhuffushi","Thinadhoo"],
  mongolia: ["Ulaanbaatar","Erdenet","Darkhan","Choibalsan","Murun","Bayankhongor","Ulgii"],
  myanmar: ["Yangon","Mandalay","Naypyidaw","Mawlamyine","Bago","Pathein","Myitkyina","Taunggyi"],
  nepal: ["Kathmandu","Pokhara","Lalitpur","Bharatpur","Biratnagar","Birgunj","Dharan","Hetauda"],
  "north-korea": ["Pyongyang","Hamhung","Chongjin","Nampo","Wonsan","Sinuiju","Tanchon"],
  philippines: ["Manila","Quezon City","Davao","Cebu","Zamboanga","Antipolo","Pasig","Taguig","Makati","Cagayan de Oro","Parañaque","Cotabato"],
  singapore: ["Singapore","Jurong East","Woodlands","Tampines","Sengkang","Punggol","Bukit Batok"],
  "south-korea": ["Seoul","Busan","Incheon","Daegu","Daejeon","Gwangju","Suwon","Ulsan","Changwon","Seongnam"],
  "sri-lanka": ["Colombo","Kandy","Galle","Jaffna","Negombo","Batticaloa","Trincomalee","Anuradhapura"],
  taiwan: ["Taipei","Kaohsiung","Taichung","Tainan","Hsinchu","Keelung","Taoyuan","Chiayi"],
  tajikistan: ["Dushanbe","Khujand","Kulob","Qurghonteppa","Istaravshan","Vahdat"],
  thailand: ["Bangkok","Chiang Mai","Pattaya","Phuket","Hat Yai","Nakhon Ratchasima","Udon Thani","Khon Kaen","Chon Buri","Nonthaburi"],
  "timor-leste": ["Dili","Baucau","Maliana"],
  turkmenistan: ["Ashgabat","Turkmenabat","Dasoguz","Mary","Balkanabat","Bayramaly"],
  uzbekistan: ["Tashkent","Samarkand","Namangan","Andijan","Bukhara","Nukus","Fergana","Karshi","Kokand","Urgench"],
  vietnam: ["Hanoi","Ho Chi Minh City","Da Nang","Hai Phong","Can Tho","Bien Hoa","Hue","Nha Trang","Buon Ma Thuot","Vung Tau"],
  albania: ["Tirana","Durres","Vlore","Shkoder","Fier","Korce","Berat","Lushnje"],
  austria: ["Vienna","Graz","Linz","Salzburg","Innsbruck","Klagenfurt","Villach","Wels"],
  belgium: ["Brussels","Antwerp","Ghent","Charleroi","Liege","Bruges","Namur","Leuven","Molenbeek","Mechelen"],
  "bosnia-and-herzegovina": ["Sarajevo","Banja Luka","Tuzla","Zenica","Mostar","Bihac","Bijeljina","Trebinje"],
  bulgaria: ["Sofia","Plovdiv","Varna","Burgas","Ruse","Stara Zagora","Pleven","Sliven"],
  croatia: ["Zagreb","Split","Rijeka","Osijek","Zadar","Slavonski Brod","Pula","Karlovac"],
  cyprus: ["Nicosia","Limassol","Larnaca","Famagusta","Paphos","Kyrenia"],
  "czech-republic": ["Prague","Brno","Ostrava","Plzen","Liberec","Olomouc","Ceske Budejovice","Hradec Kralove"],
  denmark: ["Copenhagen","Aarhus","Odense","Aalborg","Esbjerg","Randers","Kolding","Horsens"],
  finland: ["Helsinki","Espoo","Tampere","Vantaa","Oulu","Turku","Jyvaskyla","Lahti"],
  france: ["Paris","Marseille","Lyon","Toulouse","Nice","Nantes","Strasbourg","Montpellier","Bordeaux","Lille","Rennes","Reims"],
  germany: ["Berlin","Hamburg","Munich","Cologne","Frankfurt","Stuttgart","Dusseldorf","Leipzig","Dortmund","Essen","Bremen","Dresden","Hanover","Nuremberg","Duisburg"],
  greece: ["Athens","Thessaloniki","Patras","Piraeus","Larissa","Heraklion","Volos","Ioannina"],
  hungary: ["Budapest","Debrecen","Miskolc","Szeged","Pecs","Gyor","Nyiregyhaza","Kecskemet"],
  ireland: ["Dublin","Cork","Limerick","Galway","Waterford","Drogheda","Dundalk","Swords"],
  italy: ["Rome","Milan","Naples","Turin","Palermo","Genoa","Bologna","Florence","Bari","Catania","Venice","Verona"],
  kosovo: ["Pristina","Prizren","Peja","Mitrovica","Gjilan","Ferizaj","Gjakova"],
  latvia: ["Riga","Daugavpils","Liepaja","Jelgava"],
  lithuania: ["Vilnius","Kaunas","Klaipeda","Siauliai"],
  luxembourg: ["Luxembourg City","Esch-sur-Alzette","Differdange"],
  malta: ["Valletta","Birkirkara","Qormi"],
  moldova: ["Chisinau","Tiraspol","Balti","Bender"],
  montenegro: ["Podgorica","Niksic","Herceg Novi","Bijelo Polje"],
  netherlands: ["Amsterdam","Rotterdam","The Hague","Utrecht","Eindhoven","Tilburg","Groningen","Almere","Breda","Nijmegen"],
  "north-macedonia": ["Skopje","Bitola","Kumanovo","Prilep","Tetovo","Ohrid","Veles"],
  norway: ["Oslo","Bergen","Trondheim","Stavanger","Drammen","Fredrikstad","Kristiansand"],
  poland: ["Warsaw","Krakow","Lodz","Wroclaw","Poznan","Gdansk","Szczecin","Bydgoszcz","Lublin","Katowice"],
  portugal: ["Lisbon","Porto","Amadora","Braga","Setubal","Coimbra","Funchal","Almada"],
  romania: ["Bucharest","Cluj-Napoca","Timisoara","Iasi","Constanta","Craiova","Brasov","Galati"],
  russia: ["Moscow","Saint Petersburg","Novosibirsk","Yekaterinburg","Kazan","Nizhny Novgorod","Chelyabinsk","Samara","Ufa","Rostov-on-Don","Omsk","Krasnoyarsk"],
  serbia: ["Belgrade","Novi Sad","Nis","Kragujevac","Subotica","Zrenjanin"],
  slovakia: ["Bratislava","Kosice","Presov","Zilina"],
  slovenia: ["Ljubljana","Maribor","Celje","Kranj"],
  spain: ["Madrid","Barcelona","Valencia","Seville","Zaragoza","Malaga","Murcia","Palma","Las Palmas","Bilbao","Alicante","Cordoba"],
  sweden: ["Stockholm","Gothenburg","Malmo","Uppsala","Vasteras","Orebro","Linkoping"],
  switzerland: ["Zurich","Geneva","Basel","Bern","Lausanne","Winterthur","St. Gallen"],
  ukraine: ["Kyiv","Kharkiv","Odessa","Dnipro","Donetsk","Zaporizhzhia","Lviv","Kryvyi Rih","Mykolaiv","Mariupol"],
  argentina: ["Buenos Aires","Cordoba","Rosario","Mendoza","La Plata","Tucuman","Mar del Plata","Salta","Santa Fe","San Juan"],
  bolivia: ["La Paz","Santa Cruz","Cochabamba","Sucre","Oruro","Potosi","Tarija"],
  brazil: ["Sao Paulo","Rio de Janeiro","Brasilia","Salvador","Fortaleza","Belo Horizonte","Manaus","Curitiba","Recife","Porto Alegre","Belem","Goiania"],
  chile: ["Santiago","Valparaiso","Concepcion","Antofagasta","Temuco","Rancagua","Talca","Arica"],
  colombia: ["Bogota","Medellin","Cali","Barranquilla","Cartagena","Cucuta","Bucaramanga","Pereira","Santa Marta","Ibague"],
  "costa-rica": ["San Jose","Alajuela","Cartago","Heredia","Liberia","Limon","Puntarenas"],
  cuba: ["Havana","Santiago de Cuba","Camaguey","Holguin","Guantanamo","Santa Clara","Las Tunas"],
  "dominican-republic": ["Santo Domingo","Santiago","La Romana","San Pedro de Macoris","San Cristobal","Puerto Plata"],
  ecuador: ["Guayaquil","Quito","Cuenca","Santo Domingo","Machala","Duran","Manta","Ambato"],
  "el-salvador": ["San Salvador","Santa Ana","San Miguel","Soyapango","Mejicanos","Apopa"],
  guatemala: ["Guatemala City","Mixco","Villa Nueva","San Juan Sacatepequez","Quetzaltenango","Escuintla"],
  guyana: ["Georgetown","Linden","New Amsterdam","Anna Regina"],
  haiti: ["Port-au-Prince","Cap-Haitien","Gonaives","Saint-Marc"],
  honduras: ["Tegucigalpa","San Pedro Sula","La Ceiba","Choloma","El Progreso","Choluteca"],
  jamaica: ["Kingston","Montego Bay","Portmore","Spanish Town"],
  mexico: ["Mexico City","Guadalajara","Monterrey","Puebla","Tijuana","Leon","Juarez","Zapopan","Nezahualcoyotl","Merida","Chihuahua"],
  nicaragua: ["Managua","Leon","Masaya","Matagalpa","Chinandega","Granada"],
  panama: ["Panama City","San Miguelito","Tocumen","David","Arraijan","Colon"],
  paraguay: ["Asuncion","Ciudad del Este","San Lorenzo","Luque","Capiatá","Fernando de la Mora"],
  peru: ["Lima","Arequipa","Trujillo","Chiclayo","Iquitos","Piura","Cusco","Huancayo"],
  suriname: ["Paramaribo","Lelydorp","Nieuw Nickerie","Moengo"],
  "trinidad-and-tobago": ["Port of Spain","San Fernando","Chaguanas","Arima"],
  uruguay: ["Montevideo","Salto","Paysandu","Las Piedras","Rivera","Maldonado"],
  venezuela: ["Caracas","Maracaibo","Valencia","Barquisimeto","Maracay","Ciudad Guayana","San Cristobal","Maturin"],
  fiji: ["Suva","Nadi","Lautoka","Labasa"],
  "new-zealand": ["Auckland","Wellington","Christchurch","Hamilton","Tauranga","Dunedin","Palmerston North"],
  "papua-new-guinea": ["Port Moresby","Lae","Mount Hagen","Madang"],
  "solomon-islands": ["Honiara","Gizo","Auki"],
  vanuatu: ["Port Vila","Luganville","Norsup"],
};

const BASE = "https://prayer.souqalmadina.com.pk";

export default function sitemap(): MetadataRoute.Sitemap {
  const urls: MetadataRoute.Sitemap = [
    { url: BASE, changeFrequency: "daily", priority: 1 },
    { url: `${BASE}/countries`, changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/tasbih`, changeFrequency: "monthly", priority: 0.5 },
    { url: `${BASE}/qibla`, changeFrequency: "monthly", priority: 0.5 },
  ];

  for (const [countrySlug, cities] of Object.entries(countries)) {
    urls.push({ url: `${BASE}/${countrySlug}`, changeFrequency: "daily", priority: 0.8 });
    for (const city of cities) {
      urls.push({
        url: `${BASE}/${countrySlug}/${city.toLowerCase().replace(/ /g, "-")}`,
        changeFrequency: "daily",
        priority: countrySlug === "pakistan" ? 0.9 : 0.7,
        lastModified: new Date(),
      });
    }
  }

  return urls;
}